//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.09 at 05:42:38 ���� CST 
//


package com.sltunion.cloudy.vo.json;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.sltunion.cloudy.common.utils.XmlParseUtil;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="url">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockerBigJsFlag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="lockerBigJsUrl">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lockerBigSafeFlag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="lockerBigSafeUrl">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flag",
    "url",
    "lockerBigJsFlag",
    "lockerBigJsUrl",
    "lockerBigSafeFlag",
    "lockerBigSafeUrl"
})
@XmlRootElement(name = "message")
public class HomePageXml {

    @XmlElement(required = true)
    protected Integer flag;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected Integer lockerBigJsFlag;
    @XmlElement(required = true)
    protected String lockerBigJsUrl;
    @XmlElement(required = true)
    protected Integer lockerBigSafeFlag;
    @XmlElement(required = true)
    protected String lockerBigSafeUrl;

    /**
     * Gets the value of the flag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFlag(Integer value) {
        this.flag = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the lockerBigJsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockerBigJsFlag() {
        return lockerBigJsFlag;
    }

    /**
     * Sets the value of the lockerBigJsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockerBigJsFlag(Integer value) {
        this.lockerBigJsFlag = value;
    }

    /**
     * Gets the value of the lockerBigJsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockerBigJsUrl() {
        return lockerBigJsUrl;
    }

    /**
     * Sets the value of the lockerBigJsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockerBigJsUrl(String value) {
        this.lockerBigJsUrl = value;
    }

    /**
     * Gets the value of the lockerBigSafeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLockerBigSafeFlag() {
        return lockerBigSafeFlag;
    }

    /**
     * Sets the value of the lockerBigSafeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLockerBigSafeFlag(Integer value) {
        this.lockerBigSafeFlag = value;
    }

    /**
     * Gets the value of the lockerBigSafeUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockerBigSafeUrl() {
        return lockerBigSafeUrl;
    }

    /**
     * Sets the value of the lockerBigSafeUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockerBigSafeUrl(String value) {
        this.lockerBigSafeUrl = value;
    }
    
    
    public static void main(String[] args) {
    	HomePageXml driverPageXml = new HomePageXml();
		driverPageXml.setFlag(0);
		driverPageXml.setUrl("0");
		driverPageXml.setLockerBigJsFlag(0);
		driverPageXml.setLockerBigJsUrl("0");
		driverPageXml.setLockerBigSafeFlag(0);
		driverPageXml.setLockerBigSafeUrl("0");
		String url = XmlParseUtil.marshal(driverPageXml, HomePageXml.class);
		System.out.println(url);
	}
}
